### ISSUE TITLE
Respect dark mode system preference

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/tinypilot#1091]
I spoke to a customer who prefers dark mode and had to use the DarkReader extension for TinyPilot.

There's a lot we could adjust to get dark mode working, but they said that a good 80% solution would be just to fix the background, which I think is as easy as just adding this CSS rule to [style.css](https://github.com/tiny-pilot/tinypilot/blob/80f8975802d88f8360922bef38377c3cf4c0979c/app/static/css/style.css).

```css
 --brand-logo-accent-color: #232b32;

@media (prefers-color-scheme: dark) {
  body {
    background: var(--brand-dark-background);
  }
}
```
