### ISSUE TITLE
uStream compilation error

### ISSUE THREAD

**Issue by yeyeto2788** [tiny-pilot/tinypilot#888]
## uStreamer fails while compiling on 32-bit ARMv6
Briefly summarize the problem you're experiencing.

## What's the behavior that you expect?

*Compilation goes smoothly and my device outputs signal from HDMI* 😋 

## What's happening instead?

*Ansible reports that failed while compiling the software*

## What are the steps to reproduce this behavior?

1. Create `tinypilot` user by:
    `sudo useradd --create-home --system --user-group tinypilot`
2. Create `/home/tinypilot/setting.yml` with the following information:
    ```yaml
    ustreamer_capture_device: "tc358743"
    ustreamer_use_dv_timings: true
    ustreamer_desired_fps: 15
    ustreamer_drop_same_frames: 15
    ustreamer_port: 8001
    ustreamer_persistent: true
    ustreamer_encoder: omx
    ustreamer_format: uyvy
    ustreamer_resolution: 1920x720
    ```
3. Change ownership of the file:
    ```console
    sudo chown tinypilot:tinypilot "${TINYPILOT_SETTINGS_FILE}"
    ```
4. Set some variable before install
    ```console
    USE_TC358743_DEFAULTS=y
    TINYPILOT_SETTINGS_FILE="/home/tinypilot/settings.yml"
    ```
5. Install super tinypilot:
    ```console
    curl --silent --show-error https://raw.githubusercontent.com/mtlynch/tinypilot/master/quick-install | bash -
    ```

## Screenshots

*Raspberry pi OS lite configuration*
![raspberry_imager_settings](https://user-images.githubusercontent.com/6363686/149307155-da70b882-6d50-4296-ac4f-dbb26998ff61.png)

## Logs
Line 437 of the log file below shows the error 😢 
[installation_001.log](https://github.com/tiny-pilot/tinypilot/files/7861768/installation_001.log)
